# Generated by Django 2.1.2 on 2019-02-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('data_location', models.CharField(default='/img_searches/0', max_length=50)),
                ('received', models.BooleanField(default=False)),
                ('analyzed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('post_date',),
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_lib', models.URLField()),
                ('count', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('search', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='urls', to='BackEnd.ClientSearch')),
            ],
            options={
                'get_latest_by': 'count',
            },
        ),
    ]
