# Generated by Django 2.1.2 on 2019-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='result_lib',
            field=models.CharField(max_length=100),
        ),
    ]
